* Inspiration for GUI (very similar)
https://github.com/gusmanb/logicanalyzer

* Implement comparers for Addiction class
Maybe I would need to sort 'em by SortedSet.  For now they are in a generic
hashset.

* See compiled bindings
https://docs.avaloniaui.net/docs/data-binding/compiledbindings

why use compiled bindings?
https://www.codeproject.com/Articles/1161127/Why-is-reflection-slow

* use reactiveui?
https://www.reactiveui.net/docs/handbook/view-models/

* use transaction to return last insert rowid?

* see if you can make a coerce to addiction of addictionvm

* maybe don't use hours and just record dates
* fix realtive zooming
* disallow date after now in database and everywhere
* refactor
create userControls

see if failure and abstinence should be separate controls

maybe they should be separate and through interface they will be united into
third one
* Maybe use Tapped event on addiction title border
Get rid of hacky button
* dragndrop for rows
* save order to database
* focus elements right in dialogs and handle enter in textboxes
* When editing addiction title, it is not changed in notes
use notifypropertychanged?
* optimizations
- invoke property changed only if the value was changed
- Instead of doing Addiction.UpdateFailure subscribe to changes on FailedAt in insert
- see where to use batch update
* make global now
subscribe to updates of it
* try avalonstudio
https://github.com/VitalElement/AvalonStudio
this might be good for style development of avalonia
or just use developer tools?
